export const APP_ICONS = {
  driver: 'healthicons:truck-driver',
  vehicle: 'mdi:truck',
  job: 'mdi:bookmark',
  trip: 'mdi:road-variant',
  customer: 'mdi:office-building',
  transporter: 'mdi:truck-delivery',
  pump: 'mdi:gas-station',
  part: 'mdi:cube',
  expense: 'mdi:cash-multiple',
  calendar: 'mdi:calendar-clock',
  user: 'mdi:account-check',
  users: 'mdi:account-multiple',
  vendor: 'mdi:store',
  invoice: 'mdi:receipt-text',
  workOrder: 'map:car-repair',
  purchaseOrder: 'mdi:file-document-outline',
  tyre: 'mingcute:tyre-line',
  dashboard: 'mdi:view-dashboard',
  mechanic: 'mdi:account-hard-hat',
  cart: 'mdi:cart',
};
