export const INVOICE_STATUS = {
  PENDING: 'Pending',
  PARTIAL_RECEIVED: 'Partial Received',
  RECEIVED: 'Received',
  OVERDUE: 'Overdue',
  CANCELLED: 'Cancelled',
};

export const INVOICE_STATUS_COLOR = {
  [INVOICE_STATUS.RECEIVED]: 'success',
  [INVOICE_STATUS.PARTIAL_RECEIVED]: 'info',
  [INVOICE_STATUS.PENDING]: 'warning',
  [INVOICE_STATUS.OVERDUE]: 'error',
  [INVOICE_STATUS.CANCELLED]: 'default',
};

export const INVOICE_STATUS_OPTIONS = [
  { value: INVOICE_STATUS.RECEIVED, label: INVOICE_STATUS.RECEIVED },
  { value: INVOICE_STATUS.PARTIAL_RECEIVED, label: INVOICE_STATUS.PARTIAL_RECEIVED },
  { value: INVOICE_STATUS.PENDING, label: INVOICE_STATUS.PENDING },
  { value: INVOICE_STATUS.OVERDUE, label: INVOICE_STATUS.OVERDUE },
  { value: INVOICE_STATUS.CANCELLED, label: INVOICE_STATUS.CANCELLED },
];
